apiPackage: com.github.simonhauck.unofficial.nordigen.api
artifactId: unofficial-nordigen-api-java
groupId: com.github.simonhauck
artifactVersion: 1.7.0
artifactUrl: https://github.com/simonhauck/unofficial-nordigen-api-java
serializationLibrary: gson
artifactDescription: Nordigen api
developerName: Simon Hauck
library: feign

